version: 0.2

phases:
install:
    runtime-versions:
      nodejs: 12
    commands:
      # install terraform binary
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}
      - terraform init
      - terraform apply -auto-approve
artifacts:
  files:
    - '**/*'