version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands: 
      - wget -nv https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip
      - unzip terraform_0.14.7_linux_amd64.zip
      - mv terraform_0.11.11_linux_amd64 /usr/local/bin/
  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}
      - terraform init
      - terraform apply -auto-approve
artifacts:
  files:
    - '**/*'