version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands: 
      - wget -nv https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip
      - unzip terraform_0.14.7_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - terraform init
  build:
    commands:
      - terraform $TF_COMMAND -auto-approve
artifacts:
  files:
    - '**/*'